### ISSUE TITLE
Crash on sending message

### ISSUE THREAD

**Issue by billdacat** [ably/demo-mobile-android#6] opened 2016-08-12 13:49 UTC
Can login to the app, send a message, but right after I send a message, the app crashes:

I/System.out: (INFO): TokenAuth.authorise(): using cached token; expires = 1471051651986
I/System.out: (INFO): TokenAuth.getEncodedToken(): 
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.ablydemo, PID: 2251
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: org.msgpack.core.MessageTypeException: Expected String, but got Map (81)
                      at org.msgpack.core.MessageUnpacker.unexpected(MessageUnpacker.java:472)
                      at org.msgpack.core.MessageUnpacker.unpackRawStringHeader(MessageUnpacker.java:1179)
                      at org.msgpack.core.MessageUnpacker.unpackString(MessageUnpacker.java:916)
                      at io.ably.lib.types.BaseMessage.readField(BaseMessage.java:176)
                      at io.ably.lib.types.PresenceMessage.readMsgpack(PresenceMessage.java:108)
                      at io.ably.lib.types.PresenceMessage.fromMsgpack(PresenceMessage.java:120)
                      at io.ably.lib.types.PresenceSerializer.readMsgpackArray(PresenceSerializer.java:30)
                      at io.ably.lib.types.PresenceSerializer.readMsgpack(PresenceSerializer.java:37)
                      at io.ably.lib.types.PresenceSerializer$PresenceBodyHandler.handleResponseBody(PresenceSerializer.java:105)
                      at io.ably.lib.types.PresenceSerializer$PresenceBodyHandler.handleResponseBody(PresenceSerializer.java:94)
                      at io.ably.lib.http.PaginatedQuery.handleResponse(PaginatedQuery.java:114)
                      at io.ably.lib.http.PaginatedQuery.handleResponse(PaginatedQuery.java:23)
                      at io.ably.lib.http.Http.httpExecute(Http.java:392)
                      at io.ably.lib.http.Http.ablyHttpExecute(Http.java:283)
                      at io.ably.lib.http.Http.get(Http.java:207)
                      at io.ably.lib.http.PaginatedQuery.get(PaginatedQuery.java:49)
                      at io.ably.lib.realtime.Presence.history(Presence.java:466)
                      at io.ably.demo.connection.Connection$2.doInBackground(Connection.java:110)
                      at android.os.AsyncTask$2.call(AsyncTask.java:304)

**Comment by stannedelchev** [comment] 2016-08-15 06:52
I don't reproduce this at the moment. But the issue seems like it might be related to https://github.com/ably/ably-java/issues/112 . If you get the same exception again, would you try using the latest `main` branch from https://github.com/ably/ably-java and retrying?
1. Build the latest jar from https://github.com/ably/ably-java
2. Replace the `lib-full-0.8.2.jar` in `demo-mobile-android/app/libs`
3. Update the `dependencies` section in `demo-mobile-android/app/build.gradle` to use the new jar, instead of the official library. 
   This can be done either 
   - by hand via `compile files('libs/lib-full-0.8.2.jar')` or
   - by using Android Studio's `right click on app -> Open Module Settings -> Dependencies`

**Comment by billdacat** [comment] 2016-08-21 03:36
Sorry for the delayed reply, was on vacation.  Built the lib-full jar and replaced it, now crashing when sending a message with this error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.ablydemo, PID: 2389
                  java.lang.IndexOutOfBoundsException: getChars (-1 ... 0) starts before 0
                      at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
                      at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1147)
                      at android.text.TextUtils.getChars(TextUtils.java:89)
                      at android.text.TextUtils.substring(TextUtils.java:280)
                      at android.view.inputmethod.BaseInputConnection.getSelectedText(BaseInputConnection.java:531)
                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:300)
                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by mattheworiordan** [comment] 2016-08-24 10:02
@stannedelchev any ideas here?

**Comment by stannedelchev** [comment] 2016-08-24 18:36
I tried to reproduce this with the latest from `main` and again, couldn't. 😞 
The call stack doesn't show any Ably\* or demo\* methods. The issue looks like something related to text selection, text clearing, input...sorry, I'm not much help here. 
Maybe @paddybyers or @tcard can lend a hand?

@billdacat What device are you using? It would be great if you can provide some sort of screen recording or reproduction steps. The full log output of the app should also help.

**Comment by billdacat** [comment] 2016-10-09 02:36
Apologies for the long delay on this - got wrapped up in other aspects of my project.

Here's a screen recording of the crashes.

https://drive.google.com/file/d/0B-95G_YBy-dkcVEtcVpna2NyVFU/view?usp=sharing

**Comment by mattheworiordan** [comment] 2016-10-18 11:13
@stannedelchev any thoughts?

**Comment by stannedelchev** [comment] 2016-10-28 12:55
I'm out of office and don't have access to my development machine, I'll be back next week and try to reproduce this again.

**Comment by funkyboy** [comment] 2018-03-13 15:09
This doesn't seem to happen anymore. Closing this issue. Please reopen if needed.

**Closed as completed by funkyboy** 2018-03-13 15:09 UTC
Labels: bug
