### ISSUE TITLE
Typing indicator does not work

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#5] opened 2016-08-05 10:32 UTC

**Comment by stannedelchev** [comment] 2016-08-10 06:47
@mattheworiordan Can you elaborate on this? I'm not able to reproduce the issue.
Typing in the Heroku app shows the typing indicator in Android and vice versa. 
After a few seconds both indicators hide. Am I missing something?

**Comment by mattheworiordan** [comment] 2016-08-12 14:31
Perhaps it's just a styling thing, it's light grey text on a light grey background. Could you make the text slightly darker or ideally the same style as the cordova app with a lozenge?

**Comment by stannedelchev** [comment] 2016-08-15 06:29
OK, fixed in 70f3d8952f205ac3e8d6390da510ebffd606856b.

**Closed as completed by stannedelchev** 2016-08-15 06:29 UTC
Labels: bug
