### ISSUE TITLE
Review demo feedback

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#1] opened 2016-03-22 11:29 UTC
@stannedelchev I've reviewed the demo on Android and it's superb, thanks.  I have the following feedback:
- [x] Can pressing enter please proceed / submit the form i.e. on the first page, I have to hide the keyboard after typing my handle name and hit the button instead of just hitting the enter button on the keyboard.  The same issue applies to the chat interface.
- [x] When I entered for the first time, I saw "You entered the channel today at XX:XX" twice.  Are you using the untilAttach functionality for history queries?
- [x] When clicking on the messages can the keyboard disappear.  The keyboard takes up all the space yet if you are not typing a message it should disappear.  Equally, when you enter the messaging screen for the first time it should not show the keyboard until the message box gets focus.
- [x] For some reason the backspace key does not work when entering a handle name.  This may be just an emulator issue though.
- [x]  I went to airplane mode and it seemed to stay connected (perhaps this doesn't work in emulators?). I would have expected the disconnected event to kick in.  Do you know if the Java library detects OS network changes, if not, we could add that.  However, it should entered disconnected anyway within a short while as the heartbeat would be missing, that didn't happen. If there is a better way to test this please advise.
- [x] What happens if there are more Handles than can fit on the screen?
- [x] I am not sure the Ably.io sample chat application head is necessary

**Comment by stannedelchev** [comment] 2016-03-22 19:35
```
Can pressing enter please proceed / submit the form i.e. on the first page, I have to hide the keyboard after typing my handle name and hit the button instead of just hitting the enter button on the keyboard. The same issue applies to the chat interface.
```

I added a fix in `main` that enables the user to use the "Enter" key on a physical keyboard to join a channel or send a message, and also let's the user join a channel without having to dismiss the keyboard. Re: the second part of this issue, on a real device, when you tap on the software keyboard there are no issues - the keyboard hides successfully. You can simulate that in the emulator by using your mouse to click on the keyboard keys and finally clicking on the "next"/"submit" arrow in the bottom corner of the keyboard. 
Also, on a real device the keyboard isn't opened automatically when you enter the chat screen.

```
When I entered for the first time, I saw "You entered the channel today at XX:XX" twice. Are you using the untilAttach functionality for history queries?
```

Yes, `until_attach` is currently set to `false`, because there were some issues with that functionality the last couple of weeks, so I just disabled it.

```
 When clicking on the messages can the keyboard disappear. The keyboard takes up all the space yet if you are not typing a message it should disappear. Equally, when you enter the messaging screen for the first time it should not show the keyboard until the message box gets focus.
```

On my real device, the keyboard is not opened automatically when you enter the chat screen, so this issue doesn't exist. In the emulator however, it's open.
I can force the keyboard to stay hidden unless the user explicitly opens it, but I think this is more of an emulator issue.

```
For some reason the backspace key does not work when entering a handle name. This may be just an emulator issue though.
```

I wasn't able to reproduce this - neither by tapping the "backspace" key in the soft keyboard on the real device, nor by pressing the physical "backspace" key on my laptop's keyboard, nor by clicking the "backspace" key in the emulator.

```

 I went to airplane mode and it seemed to stay connected (perhaps this doesn't work in emulators?). I would have expected the disconnected event to kick in. Do you know if the Java library detects OS network changes, if not, we could add that. However, it should entered disconnected anyway within a short while as the heartbeat would be missing, that didn't happen. If there is a better way to test this please advise.
```

From what I can see, the Java lib throws a few exceptions saying that the ably.io hostname is not reachable and then sets a `disconnected` state. I'll attach some proper logs tomorrow. We can probably handle the disconnected/suspended state better in the app anyway. Maybe there's some way to test this with unit or system tests, but I'm not familiar with the library enough to give suggestions.

```
 What happens if there are more Handles than can fit on the screen?
```

I tested this and a scrollbar shows up, so the user scrolls just fine.

```
 I am not sure the Ably.io sample chat application head is necessary
```

This is now fixed in `main` as well.

**Comment by stannedelchev** [comment] 2016-05-24 07:13
I pushed a few fixes in `main`. From what I see, the lib notices the connection is down after about a minute, then the app gets the `disconnected` event and shows an error to the user. Once airplane mode is off, the lib takes some to come back online as well.

**Comment by mattheworiordan** [comment] 2016-05-24 22:19
> I pushed a few fixes in main. From what I see, the lib notices the connection is down after about a minute, then the app gets the disconnected event and shows an error to the user.

Yup, I believe we are waiting on https://github.com/ably/ably-java/pull/125 to be merged in, but unfortunately it's blocked right now as @paddybyers has to get the tests working again for Android.

**Comment by funkyboy** [comment] 2018-03-13 15:30
Disconnected event is handled correctly now. Closing.

**Closed as completed by funkyboy** 2018-03-13 15:30 UTC
Labels: bug, enhancement
